### ISSUE TITLE
Click on chart bar returns last item but not clicked one.

### ISSUE THREAD

**Issue by ihar-paliashchuk** [tradingview/lightweight-charts-android#73] opened 2021-08-25 08:07 UTC
Hi everyone, I have an issue - when clicking on histogram serries I receive the last HistogramData and current point on the screen. Is this an issue or intended behavior? I expect to return a HistogramData which I click.
If I long click on HistogramData and after a simple click then HistogramData is right, which I clicked. 

My setup:

```
lateinit var histogramSeries: SeriesApi


chart.api.applyOptions {
                layout = layoutOptions {
                    crosshair = CrosshairOptions(
                        vertLine = CrosshairLineOptions(visible = false, labelVisible = false),
                        horzLine = CrosshairLineOptions(visible = false, labelVisible = false)
                    )
                    leftPriceScale = PriceScaleOptions(visible = false)
                    rightPriceScale = PriceScaleOptions(visible = false)
                    handleScale = HandleScaleOptions(
                        mouseWheel = false,
                        pinch = false,
                        axisPressedMouseMove = AxisPressedMouseMoveOptions(time = false, price = false),
                        axisFloatClickReset = false)
                    timeScale = TimeScaleOptions(
                        borderVisible = false,
                        fixLeftEdge = true,
                        fixRightEdge = true,
                        visible = false
                    )
                    handleScroll = HandleScrollOptions(
                        mouseWheel = false,
                        pressedMouseMove = false,
                        horzTouchDrag = false,
                        vertTouchDrag = false
                    )
                    grid = gridOptions {
                        vertLines = GridLineOptions(visible = false)
                        horzLines = GridLineOptions(visible = false)
                    }
                }
            }

            chart.api.addHistogramSeries(
                options = HistogramSeriesOptions(priceLineVisible = false),
                onSeriesCreated = { series ->
                    histogramSeries = series
                }
            )

            val data = listOf(
                HistogramData(Time.BusinessDay(2019, 6, 11), 40.01f),
                HistogramData(Time.BusinessDay(2019, 6, 12), 52.38f),
                HistogramData(Time.BusinessDay(2019, 6, 13), 36.30f),
                HistogramData(Time.BusinessDay(2019, 6, 14), 34.48f),
                WhitespaceData(Time.BusinessDay(2019, 6, 15)),
                WhitespaceData(Time.BusinessDay(2019, 6, 16)),
                HistogramData(Time.BusinessDay(2019, 6, 17), 41.50f),
                HistogramData(Time.BusinessDay(2019, 6, 18), 34.82f)
            )

            histogramSeries.setData(data)
            chart.api.timeScale.fitContent()

            chart.api.subscribeClick {
                 Log.w("", it.toString())
            }
}
```

**Comment by timocov** [comment] 2021-08-25 13:45
I think this is actually duplicate of https://github.com/tradingview/lightweight-charts/issues/657. Correct me if I'm wrong.

**Closed by timocov** 2021-08-25 13:45 UTC
