### ISSUE TITLE
App crashes on Back press after adding remove series 

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/lightweight-charts-android#74] opened 2021-08-30 12:52 UTC
@timocov 

onBackpress after adding this.series.forEach(charts_view.api::removeSeries) app is crashing

please find below the code 

private fun observeViewModelData() {
        viewModel.seriesData.observe(viewLifecycleOwner, { data ->
            createSeriesWithData(data, PriceScaleId.RIGHT, charts_view.api) { series ->
                this.series.forEach(charts_view.api::removeSeries)
                this.series.clear()
                this.series.add(series)
            }
        })
    }

**Comment by makedonsky94** [comment] 2021-08-30 12:58
Please, provide crash logs for further investigation

**Comment by supriyakhankarnw18** [comment] 2021-08-30 13:00
@makedonsky94 crash logs below

 java.lang.IllegalStateException: java.lang.IllegalStateException: ReferenceError: seriesName is not defined
        at com.tradingview.lightweightcharts.api.delegates.ChartApiDelegate.removeSeries(ChartApiDelegate.kt:171)
        at com.tradingview.lightweightcharts.api.interfaces.ChartApi$DefaultImpls.removeSeries$default(ChartApi.kt:94)
        at com.tradingview.lightweightcharts.example.app.view.charts.BarChartFragment$observeViewModelData$1$1.invoke(BarChartFragment.kt:60)
        at com.tradingview.lightweightcharts.example.app.view.charts.BarChartFragment$observeViewModelData$1$1.invoke(BarChartFragment.kt:35)
        at com.tradingview.lightweightcharts.example.app.view.charts.BarChartFragment$createSeriesWithData$1.invoke(BarChartFragment.kt:136)
        at com.tradingview.lightweightcharts.example.app.view.charts.BarChartFragment$createSeriesWithData$1.invoke(BarChartFragment.kt:35)
        at com.tradingview.lightweightcharts.api.delegates.ChartApiDelegate$addBarSeries$1.invoke(ChartApiDelegate.kt:95)
        at com.tradingview.lightweightcharts.api.delegates.ChartApiDelegate$addBarSeries$1.invoke(ChartApiDelegate.kt:30)
        at com.tradingview.lightweightcharts.runtime.controller.WebMessageController$BufferElement.invoke(WebMessageController.kt:188)
        at com.tradingview.lightweightcharts.runtime.WebMessageChannel$1.onMessage(WebMessageChannel.kt:26)
        at androidx.webkit.internal.WebMessagePortImpl$1.onMessage(WebMessagePortImpl.java:111)
        at nk.a(chromium-Monochrome.aab-stable-410410173:3)
        at hR2.handleMessage(chromium-Monochrome.aab-stable-410410173:6)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6762)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: ReferenceError: seriesName is not defined
        at jsCode.SeriesFunctionManager.findSeries(file:///android_asset/com/tradingview/lightweightcharts/scripts/app/main.js:11347)
        at jsCode.Object.functionRef(file:///android_asset/com/tradingview/lightweightcharts/scripts/app/main.js:11256)
        at jsCode.FunctionManager.call(file:///android_asset/com/tradingview/lightweightcharts/scripts/app/main.js:11068)
        at jsCode.MessagePort.port.onmessage(file:///android_asset/com/tradingview/lightweightcharts/scripts/app/main.js:11822)

**Comment by makedonsky94** [comment] 2021-08-30 13:15
Duplicate of https://github.com/tradingview/lightweight-charts-android/issues/40

**Closed by makedonsky94** 2021-08-30 13:15 UTC
