### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Value is null

### ISSUE THREAD

**Issue by supriyakhankarnw18** [tradingview/lightweight-charts-android#53] opened 2021-07-23 12:57 UTC
We are facing lots of crashes due to the above error in our crash log and we are unable to reproduce at our end. Please let us know the reason for this crash.

**Comment by timocov** [comment] 2021-07-23 13:00
Duplicate of #51

**Comment by timocov** [comment] 2021-07-23 13:00
please do not create the same issues, we'll look into your problem.

**Closed by timocov** 2021-07-23 13:00 UTC
